program test_012
   use :: iso_fortran_env
   use :: forgex_test_m
   implicit none

   logical :: res = .true.

   ! x escape sequences

   print *, '=== TEST CASE 12 BEGIN ==='
   call runner_match('\x{0021}','!', .true., res)
   call runner_match('\x{0022}','"', .true., res)
   call runner_match('\x{0023}','#', .true., res)
   call runner_match('\x{0024}','$', .true., res)
   call runner_match('\x{0025}','%', .true., res)
   call runner_match('\x{0026}','&', .true., res)
   call runner_match('\x{0027}',"'", .true., res)
   call runner_match('\x{0028}','(', .true., res)
   call runner_match('\x{0029}',')', .true., res)
   call runner_match('\x{002A}','*', .true., res)
   call runner_match('\x{002B}','+', .true., res)
   call runner_match('\x{002C}',',', .true., res)
   call runner_match('\x{002D}','-', .true., res)
   call runner_match('\x{002E}','.', .true., res)
   call runner_match('\x{002F}','/', .true., res)
   call runner_match('\x{0030}','0', .true., res)
   call runner_match('\x{0031}','1', .true., res)
   call runner_match('\x{0032}','2', .true., res)
   call runner_match('\x{0033}','3', .true., res)
   call runner_match('\x{0034}','4', .true., res)
   call runner_match('\x{0035}','5', .true., res)
   call runner_match('\x{0036}','6', .true., res)
   call runner_match('\x{0037}','7', .true., res)
   call runner_match('\x{0038}','8', .true., res)
   call runner_match('\x{0039}','9', .true., res)
   call runner_match('\x{003A}',':', .true., res)
   call runner_match('\x{003B}',';', .true., res)
   call runner_match('\x{003C}','<', .true., res)
   call runner_match('\x{003D}','=', .true., res)
   call runner_match('\x{003E}','>', .true., res)
   call runner_match('\x{003F}','?', .true., res)
   call runner_match('\x{0040}','@', .true., res)
   call runner_match('\x{0041}','A', .true., res)
   call runner_match('\x{0042}','B', .true., res)
   call runner_match('\x{0043}','C', .true., res)
   call runner_match('\x{0044}','D', .true., res)
   call runner_match('\x{0045}','E', .true., res)
   call runner_match('\x{0046}','F', .true., res)
   call runner_match('\x{0047}','G', .true., res)
   call runner_match('\x{0048}','H', .true., res)
   call runner_match('\x{0049}','I', .true., res)
   call runner_match('\x{004A}','J', .true., res)
   call runner_match('\x{004B}','K', .true., res)
   call runner_match('\x{004C}','L', .true., res)
   call runner_match('\x{004D}','M', .true., res)
   call runner_match('\x{004E}','N', .true., res)
   call runner_match('\x{004F}','O', .true., res)
   call runner_match('\x{0050}','P', .true., res)
   call runner_match('\x{0051}','Q', .true., res)
   call runner_match('\x{0052}','R', .true., res)
   call runner_match('\x{0053}','S', .true., res)
   call runner_match('\x{0054}','T', .true., res)
   call runner_match('\x{0055}','U', .true., res)
   call runner_match('\x{0056}','V', .true., res)
   call runner_match('\x{0057}','W', .true., res)
   call runner_match('\x{0058}','X', .true., res)
   call runner_match('\x{0059}','Y', .true., res)
   call runner_match('\x{005A}','Z', .true., res)
   call runner_match('\x{0061}','a', .true., res)
   call runner_match('\x{0062}','b', .true., res)
   call runner_match('\x{0063}','c', .true., res)
   call runner_match('\x{0064}','d', .true., res)
   call runner_match('\x{0065}','e', .true., res)
   call runner_match('\x{0066}','f', .true., res)
   call runner_match('\x{0067}','g', .true., res)
   call runner_match('\x{0068}','h', .true., res)
   call runner_match('\x{0069}','i', .true., res)
   call runner_match('\x{006A}','j', .true., res)
   call runner_match('\x{006B}','k', .true., res)
   call runner_match('\x{006C}','l', .true., res)
   call runner_match('\x{006D}','m', .true., res)
   call runner_match('\x{006E}','n', .true., res)
   call runner_match('\x{006F}','o', .true., res)
   call runner_match('\x{0070}','p', .true., res)
   call runner_match('\x{0071}','q', .true., res)
   call runner_match('\x{0072}','r', .true., res)
   call runner_match('\x{0073}','s', .true., res)
   call runner_match('\x{0074}','t', .true., res)
   call runner_match('\x{0075}','u', .true., res)
   call runner_match('\x{0076}','v', .true., res)
   call runner_match('\x{0077}','w', .true., res)
   call runner_match('\x{0078}','x', .true., res)
   call runner_match('\x{0079}','y', .true., res)
   call runner_match('\x{007A}','z', .true., res)
   call runner_match('\x{00A1}','¡', .true., res)
   call runner_match('\x{00A2}','¢', .true., res)
   call runner_match('\x{00A3}','£', .true., res)
   call runner_match('\x{00A4}','¤', .true., res)
   call runner_match('\x{00A5}','¥', .true., res)
   call runner_match('\x{00A6}','¦', .true., res)
   call runner_match('\x{00A7}','§', .true., res)
   call runner_match('\x{00A8}','¨', .true., res)
   call runner_match('\x{00A9}','©', .true., res)
   call runner_match('\x{00AA}','ª', .true., res)
   call runner_match('\x{00AB}','«', .true., res)
   call runner_match('\x{00AC}','¬', .true., res)
   call runner_match('\x{00AE}','®', .true., res)
   call runner_match('\x{00AF}','¯', .true., res)
   call runner_match('\x{00B0}','°', .true., res)
   call runner_match('\x{00B1}','±', .true., res)
   call runner_match('\x{00B2}','²', .true., res)
   call runner_match('\x{00B3}','³', .true., res)
   call runner_match('\x{00B4}','´', .true., res)
   call runner_match('\x{00B5}','µ', .true., res)
   call runner_match('\x{00B6}','¶', .true., res)
   call runner_match('\x{00B7}','·', .true., res)
   call runner_match('\x{00B8}','¸', .true., res)
   call runner_match('\x{00B9}','¹', .true., res)
   call runner_match('\x{00BA}','º', .true., res)
   call runner_match('\x{00BB}','»', .true., res)
   call runner_match('\x{00BC}','¼', .true., res)
   call runner_match('\x{00BD}','½', .true., res)
   call runner_match('\x{00BE}','¾', .true., res)
   call runner_match('\x{00BF}','¿', .true., res)
   call runner_match('\x{00C0}','À', .true., res)
   call runner_match('\x{00C1}','Á', .true., res)
   call runner_match('\x{00C2}','Â', .true., res)
   call runner_match('\x{00C3}','Ã', .true., res)
   call runner_match('\x{00C4}','Ä', .true., res)
   call runner_match('\x{00C5}','Å', .true., res)
   call runner_match('\x{00C6}','Æ', .true., res)
   call runner_match('\x{00C7}','Ç', .true., res)
   call runner_match('\x{00C8}','È', .true., res)
   call runner_match('\x{00C9}','É', .true., res)
   call runner_match('\x{00CA}','Ê', .true., res)
   call runner_match('\x{00CB}','Ë', .true., res)
   call runner_match('\x{00CC}','Ì', .true., res)
   call runner_match('\x{00CD}','Í', .true., res)
   call runner_match('\x{00CE}','Î', .true., res)
   call runner_match('\x{00CF}','Ï', .true., res)
   call runner_match('\x{00D0}','Ð', .true., res)
   call runner_match('\x{00D1}','Ñ', .true., res)
   call runner_match('\x{00D2}','Ò', .true., res)
   call runner_match('\x{00D3}','Ó', .true., res)
   call runner_match('\x{00D4}','Ô', .true., res)
   call runner_match('\x{00D5}','Õ', .true., res)
   call runner_match('\x{00D6}','Ö', .true., res)
   call runner_match('\x{00D7}','×', .true., res)
   call runner_match('\x{00D8}','Ø', .true., res)


   if (res) then
      write(error_unit, *) '=== TEST CASE 12 END ==='
      stop
   else
      error stop
   end if
         

end program test_012
