name: Tested with LLVM Flang on Ubuntu

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  flang-19:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        # os: [ubuntu-22.04]
       os: [ "ubuntu-22.04", "ubuntu-24.04" ]
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Prepare repos. 
      run: |
        wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key | sudo tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc
        codename=$(lsb_release -cs)
        sudo add-apt-repository -y deb http://apt.llvm.org/$codename/ llvm-toolchain-$codename-19 main
        wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | sudo tee /etc/apt/trusted.gpg.d/kitware.gpg >/dev/null
        sudo apt-add-repository -y "deb https://apt.kitware.com/ubuntu/ $(lsb_release -cs) main"
        sudo apt update -y        
    
    - name: Install packages
      run: |
        sudo apt install -y flang-19 cmake
    
    - name: Install FPM
      uses: fortran-lang/setup-fpm@v5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Installation Check
      run: |
        flang-new-19 --version
        cmake --version
        fpm --version

    - name: Forgex test with CMake (Debug profile)
      run: |
        cmake -S . -B build -DCMAKE_Fortran_COMPILER=flang-new-19
        cmake --build build
        ctest -C Debug --test-dir build
        fpm clean --all

    - name: Forgex test with CMake (Release profile)
      run: |
        cmake -S . -B build -DCMAKE_Fortran_COMPILER=flang-new-19 -DCMAKE_BUILD_TYPE=Release
        cmake --build build
        ctest -C Release --test-dir build
        fpm clean --all

    - name: Forgex test with FPM (Debug profile)
      run: |
        fpm test --profile debug --compiler flang-new-19 --flag "-fno-backslash -cpp -DFAILED"
        fpm clean --all

    - name: Forgex test with FPM (Release profile)
      run: |
        fpm test --profile release --compiler flang-new-19 --flag "-fno-backslash -cpp -DFAILED"
