name: Tested with LLVM Flang on Ubuntu

on:
  push:
    branches: [ "main", "exp" ]
    paths-ignore:
      - 'ford/**'
      - 'README.md'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'ford/**'
      - 'README.md'
jobs:
  flang:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
       os: [ "ubuntu-latest" ]
       flang_version: [ 19,20 ] # Flang v18 is not supported.
    env:
      NO_STOP_MESSAGE: 1 
      # When a command finishes successfully, Flang prints the message 'FORTRAN STOP', so suppress this.
    container:
      image: ghcr.io/shinobuamasaki/flang-${{ matrix.flang_version }}-noble-ubuntu
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Installation Check
      run: |
        flang-new-${{ matrix.flang_version }} --version
        cmake --version
        fpm --version

    - name: Forgex test with CMake (Debug profile) and flang-${{ matrix.flang_version }}
      if: always()
      run: |
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug 2>&1 > /dev/null
        cmake --build build  > /dev/null
        ctest -C Debug --test-dir build
        fpm clean --all  2>&1 > /dev/null

    - name: Forgex test with CMake (Release profile) and flang-${{ matrix.flang_version }}
      if: always()
      run: |
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Release 2>&1 > /dev/null
        cmake --build build  > /dev/null
        ctest -C Release --test-dir build
        fpm clean --all  2>1 > /dev/null

    - name: Forgex test with FPM (Debug profile) and flang-${{ matrix.flang_version }}
      if: always()
      run: |
        fpm test --profile debug --flag "-fno-backslash -cpp -DFAILED" > /dev/null
        fpm clean --all  2>&1 > /dev/null

    - name: Forgex test with FPM (Release profile) and flang-${{ matrix.flang_version }}
      if: always()
      run: |
        fpm test --profile release --flag "-fno-backslash -cpp -DFAILED" > /dev/null
    
